apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-motd-configuration
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,V2VsY29tZSB0byBKT05BSCdzIENsdXN0ZXIuIERvbid0IHRvdWNoIHdoYXQgeW91IGRvbid0IHVuZGVyc3RhbmQuIApraW5kbHkgcmVhY2ggbWUgb24gam9uYWguaXJhbmRlQGJsdWRpdmUubmV0IGZvciBoZWxwCg==
        mode: 420
        overwrite: true
        path: /etc/motd
